/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.Vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import poo.com.sistemahotel.Controlador.GestorHabitacion;
import poo.com.sistemahotel.Controlador.GestorReserva;
import poo.com.sistemahotel.Modelo.Habitacion;
import poo.com.sistemahotel.Modelo.Reserva;

/**
 *
 * @author manue
 */
public class CancelarReserva extends javax.swing.JFrame {

        private GestorReserva gestorReserva;
        private GestorHabitacion gestorHabitacion;
        /**
         * Creates new form CancelarReserva
         */
        public CancelarReserva() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
                
                this.gestorReserva = GestorReserva.getInstanciaReserva();
                this.gestorHabitacion = GestorHabitacion.getInstanciaHabitacion();
                
                jCBReserva.setModel(Login.modeloReservas);
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLReserva = new javax.swing.JLabel();
                jCBReserva = new javax.swing.JComboBox<>();
                jBConfirmar = new javax.swing.JButton();

                jLTitulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo.setText("Cancelar Reserva");

                jPRegistro.setOpaque(false);

                jLReserva.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLReserva.setForeground(new java.awt.Color(0, 0, 0));
                jLReserva.setText("Reserva");

                jCBReserva.setBackground(new java.awt.Color(255, 255, 255));
                jCBReserva.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBReserva.setForeground(new java.awt.Color(0, 0, 0));

                jBConfirmar.setBackground(new java.awt.Color(153, 255, 153));
                jBConfirmar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBConfirmar.setForeground(new java.awt.Color(0, 0, 0));
                jBConfirmar.setText("Confirmar");
                jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBConfirmarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(140, 140, 140)
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jCBReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(216, 216, 216)
                                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(190, Short.MAX_VALUE))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLReserva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(69, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(106, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(71, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
                if(jCBReserva.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(null, "Seleccione una reserva", "Error Reserva", 0);
                }else{
                        String[] reservaCB = jCBReserva.getSelectedItem().toString().split(";");
                        String id = reservaCB[0];
                        int idSeleccionado = jCBReserva.getSelectedIndex();
                        String idHabitacion = reservaCB[1];
                        
                        Reserva reserva = gestorReserva.buscarReserva(Integer.parseInt(id));
                        Habitacion habitacion = gestorHabitacion.buscarHabitacion(Integer.parseInt(idHabitacion));
                        
                        gestorReserva.cancelarReserva(reserva);
                        Login.modeloReservas.removeElementAt(idSeleccionado);
                        
                        gestorHabitacion.cambiarEstadoHabitacion(habitacion, "disponible");

                        Login.modeloHabitaciones.addElement(habitacion.getNumero() + ", " + habitacion.getTipo() + ", $" + habitacion.getPrecioPorNoche()); 
                        
                        JOptionPane.showMessageDialog(null, "Reserva cancelada", "Confirmación Cancelación", 1);
                }
        }//GEN-LAST:event_jBConfirmarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(CancelarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new CancelarReserva().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBConfirmar;
        private javax.swing.JComboBox<String> jCBReserva;
        private javax.swing.JLabel jLReserva;
        private javax.swing.JLabel jLTitulo;
        private javax.swing.JPanel jPRegistro;
        // End of variables declaration//GEN-END:variables
}
