/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.Vista;

import java.awt.Color;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import poo.com.sistemahotel.Controlador.*;
import poo.com.sistemahotel.Modelo.*;

/**
 *
 * @author manue
 */
public class Login extends javax.swing.JFrame {

        //Combo Box
        public static DefaultComboBoxModel<String> modeloHabitaciones;
        public static DefaultComboBoxModel<String> modeloClientes;
        public static DefaultComboBoxModel<String> modeloReservas;
        public static DefaultComboBoxModel<String> modeloEstancias;
        private GestorCliente gestorCliente;
        private GestorHabitacion gestorHabitacion;
        private GestorEstancia gestorEstancia;
        private GestorReserva gestorReserva;

        /**
         * Creates new form Login
         */
        public Login() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));

                modeloClientes = new DefaultComboBoxModel<>();
                modeloHabitaciones = new DefaultComboBoxModel<>();
                modeloReservas = new DefaultComboBoxModel<>();
                modeloEstancias = new DefaultComboBoxModel<>();

                this.gestorCliente = GestorCliente.getInstanciaCliente();
                this.gestorHabitacion = GestorHabitacion.getInstanciaHabitacion();
                this.gestorEstancia = GestorEstancia.getInstanciaEstancia();
                this.gestorReserva = GestorReserva.getInstanciaReserva();

                //Cargar informacion de comboBox
                modeloHabitaciones.addElement("Seleccione...");
                for (Habitacion habitacion : gestorHabitacion.getPersistenciaHabitacion().listarHabitaciones()) {
                        if (habitacion.getEstado().equalsIgnoreCase("disponible")) {
                                modeloHabitaciones.addElement(habitacion.getNumero() + ", " + habitacion.getTipo() + ", $" + habitacion.getPrecioPorNoche());
                        }
                }

                modeloReservas.addElement("Seleccione...");
                for (Reserva reserva : gestorReserva.getPersistenciaReserva().listarReservas()) {
                        modeloReservas.addElement(reserva.getIdReserva() + ", " + reserva.getEstado());
                }

                modeloClientes.addElement("Seleccione...");
                for (Cliente cliente : gestorCliente.getPersistenciaCliente().listarClientes()) {

                        modeloClientes.addElement(cliente.getNombre() + " " + cliente.getApellido() + ", " + cliente.getCedula());
                }

                modeloEstancias.addElement("Seleccione...");
                for (Estancia estancia : gestorEstancia.getPersistenciaEstancia().listarEstancias()) {
                        if (estancia.getEstado().equals("ingresado")) {
                                modeloEstancias.addElement(estancia.getIdEstancia() + ", " + estancia.getReserva().getIdReserva());
                        }
                }
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo = new javax.swing.JLabel();
                jLTitulo1 = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLCorreo = new javax.swing.JLabel();
                jTCorreo = new javax.swing.JTextField();
                jLContrasenia = new javax.swing.JLabel();
                jLNoRegistrado = new javax.swing.JLabel();
                jBRegistro = new javax.swing.JButton();
                jBInicioSesion = new javax.swing.JButton();
                jPassword = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Login");

                jLTitulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo.setForeground(new java.awt.Color(204, 153, 0));
                jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo.setText("Inicie sesión");

                jLTitulo1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo1.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo1.setText("¡Bienvenido!");

                jPRegistro.setOpaque(false);

                jLCorreo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLCorreo.setForeground(new java.awt.Color(0, 0, 0));
                jLCorreo.setText("Correo");

                jTCorreo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTCorreo.setForeground(new java.awt.Color(0, 0, 0));
                jTCorreo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTCorreoActionPerformed(evt);
                        }
                });

                jLContrasenia.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLContrasenia.setForeground(new java.awt.Color(0, 0, 0));
                jLContrasenia.setText("Contraseña");

                jLNoRegistrado.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLNoRegistrado.setForeground(new java.awt.Color(0, 0, 0));
                jLNoRegistrado.setText("¿No registrado?");

                jBRegistro.setBackground(new java.awt.Color(255, 153, 153));
                jBRegistro.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBRegistro.setForeground(new java.awt.Color(0, 0, 0));
                jBRegistro.setText("Registrarse");
                jBRegistro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBRegistroActionPerformed(evt);
                        }
                });

                jBInicioSesion.setBackground(new java.awt.Color(153, 255, 153));
                jBInicioSesion.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
                jBInicioSesion.setText("Iniciar Sesión");
                jBInicioSesion.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBInicioSesionActionPerformed(evt);
                        }
                });

                jPassword.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jPassword.setForeground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(241, 241, 241)
                                                .addComponent(jBInicioSesion)))
                                .addContainerGap(196, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroLayout.createSequentialGroup()
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addComponent(jPassword))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addContainerGap(169, Short.MAX_VALUE)
                                                .addComponent(jLNoRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBRegistro)))
                                .addGap(220, 220, 220))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLContrasenia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBInicioSesion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBRegistro)
                                        .addComponent(jLNoRegistrado))
                                .addGap(37, 37, 37))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(115, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(250, 250, 250))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(90, 90, 90))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLTitulo1)
                                .addGap(18, 18, 18)
                                .addComponent(jLTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioSesionActionPerformed
                if (jTCorreo.getText().isEmpty() || new String(jPassword.getPassword()).isEmpty()) {
                        JOptionPane.showMessageDialog(null, "¡Ingrese los datos!", "Error Espacios en Blanco", 0);
                } else {
                        boolean usuarioExiste = false;
                        String password = new String(jPassword.getPassword()).trim();
                        //Si el usuario que se ingresa es el recepcionista
                        if (jTCorreo.getText().equals("admin1") && password.equals("hol@mundo")) {
                                usuarioExiste = true;
                                MenuPrincipalRecepcionista rep = new MenuPrincipalRecepcionista();
                                this.dispose(); //Cerrar login
                                rep.setVisible(true); //Abrir menu recepcionista
                        }else{
                                //Verificar que el cliente existe y que ingresa con su correo y contraseña
                                for (Cliente cliente : gestorCliente.getPersistenciaCliente().listarClientes()) {
                                        if (cliente.getCorreo().equals(jTCorreo.getText().trim()) && cliente.getPassword().equals(password)) {
                                                usuarioExiste = true;
                                                MenuPrincipalCliente cl = new MenuPrincipalCliente();
                                                this.dispose();
                                                cl.setVisible(true);
                                                break;
                                        }
                                }
                        }

                        if (!usuarioExiste) {
                                JOptionPane.showMessageDialog(null, "¡Usuario incorrecto!", "Error Usuario", 0);
                        }
                }

        }//GEN-LAST:event_jBInicioSesionActionPerformed

        private void jBRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistroActionPerformed
                RegistroCliente registro = new RegistroCliente();
                registro.setVisible(true);
        }//GEN-LAST:event_jBRegistroActionPerformed

        private void jTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoActionPerformed

        }//GEN-LAST:event_jTCorreoActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Login().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBInicioSesion;
        private javax.swing.JButton jBRegistro;
        private javax.swing.JLabel jLContrasenia;
        private javax.swing.JLabel jLCorreo;
        private javax.swing.JLabel jLNoRegistrado;
        private javax.swing.JLabel jLTitulo;
        private javax.swing.JLabel jLTitulo1;
        private javax.swing.JPanel jPRegistro;
        private javax.swing.JPasswordField jPassword;
        private javax.swing.JTextField jTCorreo;
        // End of variables declaration//GEN-END:variables

}
