/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.Vista;

import java.awt.Color;

/**
 *
 * @author manue
 */
public class MenuPrincipalRecepcionista extends javax.swing.JFrame {

        /**
         * Creates new form MenuPrincipalRecepcionista
         */
        public MenuPrincipalRecepcionista() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo1 = new javax.swing.JLabel();
                jBIngreso = new javax.swing.JButton();
                jBFinalizarEstancia = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Menú Principal Recepcionista");

                jLTitulo1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo1.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo1.setText("Seleccione lo que desea realizar");

                jBIngreso.setBackground(new java.awt.Color(153, 255, 153));
                jBIngreso.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBIngreso.setForeground(new java.awt.Color(0, 0, 0));
                jBIngreso.setText("Registrar ingreso de cliente");
                jBIngreso.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBIngresoActionPerformed(evt);
                        }
                });

                jBFinalizarEstancia.setBackground(new java.awt.Color(255, 153, 153));
                jBFinalizarEstancia.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBFinalizarEstancia.setForeground(new java.awt.Color(0, 0, 0));
                jBFinalizarEstancia.setText("Finalizar estancia de cliente");
                jBFinalizarEstancia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBFinalizarEstanciaActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jBIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(91, 91, 91)
                                                .addComponent(jBFinalizarEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 112, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBFinalizarEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(120, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresoActionPerformed
                RegistrarIngreso ingreso = new RegistrarIngreso();
                ingreso.setVisible(true);
        }//GEN-LAST:event_jBIngresoActionPerformed

        private void jBFinalizarEstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarEstanciaActionPerformed
                FinalizarEstancia estancia = new FinalizarEstancia();
                estancia.setVisible(true);
        }//GEN-LAST:event_jBFinalizarEstanciaActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MenuPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MenuPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MenuPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MenuPrincipalRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MenuPrincipalRecepcionista().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBFinalizarEstancia;
        private javax.swing.JButton jBIngreso;
        private javax.swing.JLabel jLTitulo1;
        // End of variables declaration//GEN-END:variables
}
