/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.pantallas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class FinalizarEstancia extends javax.swing.JFrame {

        /**
         * Creates new form FinalizarEstancia
         */
        public FinalizarEstancia() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
                
                jCBCliente.setModel(Login.modeloClientes);
                jCBEstancia.setModel(Login.modeloEstancias);
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLCliente = new javax.swing.JLabel();
                jCBEstancia = new javax.swing.JComboBox<>();
                jBConfirmar = new javax.swing.JButton();
                jLEstancia = new javax.swing.JLabel();
                jCBCliente = new javax.swing.JComboBox<>();
                jLEstadoHabitacion = new javax.swing.JLabel();
                jCBEstadoHabitacion = new javax.swing.JComboBox<>();

                setTitle("Finalizar estancia del cliente");

                jLTitulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo.setText("Finalizar estancia del cliente");

                jPRegistro.setOpaque(false);

                jLCliente.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLCliente.setForeground(new java.awt.Color(0, 0, 0));
                jLCliente.setText("Cliente");

                jCBEstancia.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBEstancia.setForeground(new java.awt.Color(255, 255, 255));

                jBConfirmar.setBackground(new java.awt.Color(153, 255, 153));
                jBConfirmar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBConfirmar.setForeground(new java.awt.Color(0, 0, 0));
                jBConfirmar.setText("Confirmar");
                jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBConfirmarActionPerformed(evt);
                        }
                });

                jLEstancia.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLEstancia.setForeground(new java.awt.Color(0, 0, 0));
                jLEstancia.setText("Estancia");

                jCBCliente.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBCliente.setForeground(new java.awt.Color(255, 255, 255));

                jLEstadoHabitacion.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLEstadoHabitacion.setForeground(new java.awt.Color(0, 0, 0));
                jLEstadoHabitacion.setText("Estado de la habitación");

                jCBEstadoHabitacion.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBEstadoHabitacion.setForeground(new java.awt.Color(0, 0, 0));
                jCBEstadoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Buen estado", "Mal estado", "Deplorable" }));

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroLayout.createSequentialGroup()
                                .addContainerGap(247, Short.MAX_VALUE)
                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(217, 217, 217))
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCBEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jCBCliente, 0, 377, Short.MAX_VALUE)
                                                .addComponent(jCBEstancia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLEstancia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLEstadoHabitacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEstadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(158, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(182, 182, 182))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(140, 140, 140))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(153, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
                if(jCBCliente.getSelectedIndex() == 0 || jCBEstancia.getSelectedIndex() == 0 || jCBEstadoHabitacion.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(null, "Seleccione la información", "Error Selección", 0);
                }else{
                        String clienteId = Integer.toString(Login.buscarClientePorCorreo(jCBCliente.getSelectedItem().toString().split(";")[5]));
                        String estanciaId = jCBEstancia.getSelectedItem().toString().split(";")[0];
                        int monto = 0;
                        String estado = jCBEstadoHabitacion.getSelectedItem().toString();
                        int idSeleccionado = jCBEstancia.getSelectedIndex();
                        String estanciaSeleccionada = Login.buscarEstanciaPorId(estanciaId);
                        String reserva = Login.buscarReservaPorId(estanciaSeleccionada.split(";")[2]);
                        System.out.println(reserva);
                        String habitacionId = reserva.split(";")[1];

                        switch(estado){
                                case "Buen estado":
                                        monto = 0;
                                        break;
                                case "Mal estado":
                                        monto = 10;
                                        break;
                                case "Deplorable":
                                        monto = 50;
                                        break;
                        }
                        Login.cambiarEstadoEstancia(estanciaId, estado);
                        Login.modeloEstancias.removeElementAt(idSeleccionado);
                        Login.cambiarEstadoHabitacion(habitacionId, "disponible");

                        String habitacion = Login.buscarHabitacionPorId(habitacionId);
                        String lineaHabitacion[] = habitacion.split(";");
                        Login.modeloHabitaciones.addElement(lineaHabitacion[0] + ", " + lineaHabitacion[1] + ", $" + lineaHabitacion[2]);
                        Login.escribirArchivoEstancias();
                        Login.escribirArchivoHabitaciones();
                        JOptionPane.showMessageDialog(null, "Estancia Finalizada", "Confirmación Estancia", 1);
                        JOptionPane.showMessageDialog(null, "Monto a devolver: " + monto, "Confirmación", 1);
                        
                }
        }//GEN-LAST:event_jBConfirmarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FinalizarEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FinalizarEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FinalizarEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FinalizarEstancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FinalizarEstancia().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBConfirmar;
        private javax.swing.JComboBox<String> jCBCliente;
        private javax.swing.JComboBox<String> jCBEstadoHabitacion;
        private javax.swing.JComboBox<String> jCBEstancia;
        private javax.swing.JLabel jLCliente;
        private javax.swing.JLabel jLEstadoHabitacion;
        private javax.swing.JLabel jLEstancia;
        private javax.swing.JLabel jLTitulo;
        private javax.swing.JPanel jPRegistro;
        // End of variables declaration//GEN-END:variables
}
