/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.pantallas;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Login extends javax.swing.JFrame {
        
        //Archivos
        private static File reservas;
        private static File habitaciones;
        private static File usuarios;
        private static File reservasArchivo;
        private static File habitacionesArchivo;
        private static File estanciasArchivo;
        
        //Arreglos
        public static ArrayList<String> usuariosLista;
        public static ArrayList<String> habitacionesLista;
        public static ArrayList<String> reservasLista;
        public static ArrayList<String> estanciasLista;
        
        //Combo Box
        public static DefaultComboBoxModel<String> modeloHabitaciones;
        public static DefaultComboBoxModel<String> modeloClientes;
        public static DefaultComboBoxModel<String> modeloReservas;
        public static DefaultComboBoxModel<String> modeloEstancias;

        

        /**
         * Creates new form Login
         */
        public Login() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
               
                
                reservas = new File("src/main/resources/archivos/reservas.txt");
                habitaciones = new File("src/main/resources/archivos/habitaciones.txt");
                usuarios = new File("src/main/resources/archivos/usuarios.txt");
                reservasArchivo = new File("src/main/resources/archivos/reservas.txt");
                habitacionesArchivo = new File("src/main/resources/archivos/habitaciones.txt");
                estanciasArchivo = new File("src/main/resources/archivos/estancias.txt");
                
                usuariosLista = new ArrayList<>();
                habitacionesLista = new ArrayList<>();
                reservasLista = new ArrayList<>();
                estanciasLista = new ArrayList<>();
                modeloClientes = new DefaultComboBoxModel<>();
                modeloHabitaciones = new  DefaultComboBoxModel<>();
                modeloReservas = new DefaultComboBoxModel<>();
                modeloEstancias = new DefaultComboBoxModel<>();
                
                //Cargar informacion de los archivos
                leerArchivoUsuarios();
                leerArchivoHabitaciones();
                leerArchivoReservas();
                leerArchivoEstancias();
                
                //Cargar informacion de comboBox
                modeloHabitaciones.addElement("Seleccione...");
                for(String habitacion : habitacionesLista){
                        String[] linea = habitacion.split(";");
                        if(linea[3].equalsIgnoreCase("disponible")){
                                modeloHabitaciones.addElement(linea[0] + ", " + linea[1] + ", $" + linea[2]);
                        }
                }
                
                modeloReservas.addElement("Seleccione...");
                for(String reserva : reservasLista){
                        String[] linea = reserva.split(";");
                        modeloReservas.addElement(reserva);
                }
                
                modeloClientes.addElement("Seleccione...");
                for(String usuario : usuariosLista){
                        String[] linea = usuario.split(";");
                        if(linea[6].equals("cliente")){
                                modeloClientes.addElement(usuario);
                        }
                }
                
                modeloEstancias.addElement("Seleccione...");
                for(String estancia : estanciasLista){
                        String[] linea = estancia.split(";");
                        if(linea[3].equals("ingresado")){
                                modeloEstancias.addElement(estancia);
                        }
                }
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo = new javax.swing.JLabel();
                jLTitulo1 = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLCorreo = new javax.swing.JLabel();
                jTCorreo = new javax.swing.JTextField();
                jLContrasenia = new javax.swing.JLabel();
                jLNoRegistrado = new javax.swing.JLabel();
                jBRegistro = new javax.swing.JButton();
                jBInicioSesion = new javax.swing.JButton();
                jPassword = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Login");

                jLTitulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo.setForeground(new java.awt.Color(204, 153, 0));
                jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo.setText("Inicie sesión");

                jLTitulo1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo1.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo1.setText("¡Bienvenido!");

                jPRegistro.setOpaque(false);

                jLCorreo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLCorreo.setForeground(new java.awt.Color(0, 0, 0));
                jLCorreo.setText("Correo");

                jTCorreo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTCorreo.setForeground(new java.awt.Color(0, 0, 0));
                jTCorreo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTCorreoActionPerformed(evt);
                        }
                });

                jLContrasenia.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLContrasenia.setForeground(new java.awt.Color(0, 0, 0));
                jLContrasenia.setText("Contraseña");

                jLNoRegistrado.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLNoRegistrado.setForeground(new java.awt.Color(0, 0, 0));
                jLNoRegistrado.setText("¿No registrado?");

                jBRegistro.setBackground(new java.awt.Color(255, 153, 153));
                jBRegistro.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBRegistro.setForeground(new java.awt.Color(0, 0, 0));
                jBRegistro.setText("Registrarse");
                jBRegistro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBRegistroActionPerformed(evt);
                        }
                });

                jBInicioSesion.setBackground(new java.awt.Color(153, 255, 153));
                jBInicioSesion.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBInicioSesion.setForeground(new java.awt.Color(0, 0, 0));
                jBInicioSesion.setText("Iniciar Sesión");
                jBInicioSesion.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBInicioSesionActionPerformed(evt);
                        }
                });

                jPassword.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jPassword.setForeground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(241, 241, 241)
                                                .addComponent(jBInicioSesion)))
                                .addContainerGap(196, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRegistroLayout.createSequentialGroup()
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(175, 175, 175)
                                                .addComponent(jPassword))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addContainerGap(169, Short.MAX_VALUE)
                                                .addComponent(jLNoRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBRegistro)))
                                .addGap(220, 220, 220))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLContrasenia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBInicioSesion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBRegistro)
                                        .addComponent(jLNoRegistrado))
                                .addGap(37, 37, 37))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(115, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(250, 250, 250))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(90, 90, 90))))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLTitulo1)
                                .addGap(18, 18, 18)
                                .addComponent(jLTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioSesionActionPerformed
                if(jTCorreo.getText().isEmpty() ||new String(jPassword.getPassword()).isEmpty()){
                        JOptionPane.showMessageDialog(null, "¡Ingrese los datos!", "Error Espacios en Blanco", 0);
                }else{
                        boolean usuarioExiste = false;
                        for(int i = 0; i < usuariosLista.size(); i++){
                                String[] usuario = usuariosLista.get(i).split(";"); //Separar por ;
                                if( usuario[5].equals(jTCorreo.getText().trim()) && usuario[2].equals(new String(jPassword.getPassword()).trim()) && usuario[6].equalsIgnoreCase("recepcionista")){
                                        usuarioExiste = true;
                                        MenuPrincipalRecepcionista rep = new MenuPrincipalRecepcionista();
                                        this.dispose(); //Cerrar login
                                        rep.setVisible(true); //Abrir menu recepcionista
                                }else if(usuario[5].equals(jTCorreo.getText().trim()) && usuario[2].equals(new String(jPassword.getPassword()).trim()) && usuario[6].equalsIgnoreCase("cliente")){
                                        usuarioExiste = true;
                                        MenuPrincipalCliente cliente = new MenuPrincipalCliente();
                                        this.dispose();
                                        cliente.setVisible(true);
                                }
                        }
                        
                        if(!usuarioExiste){
                                JOptionPane.showMessageDialog(null, "¡Usuario incorrecto!", "Error Usuario", 0);
                        }
                }
                
        }//GEN-LAST:event_jBInicioSesionActionPerformed

        private void jBRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistroActionPerformed
                RegistroCliente registro = new RegistroCliente();
                registro.setVisible(true);
        }//GEN-LAST:event_jBRegistroActionPerformed

        private void jTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoActionPerformed
                
        }//GEN-LAST:event_jTCorreoActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Login().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBInicioSesion;
        private javax.swing.JButton jBRegistro;
        private javax.swing.JLabel jLContrasenia;
        private javax.swing.JLabel jLCorreo;
        private javax.swing.JLabel jLNoRegistrado;
        private javax.swing.JLabel jLTitulo;
        private javax.swing.JLabel jLTitulo1;
        private javax.swing.JPanel jPRegistro;
        private javax.swing.JPasswordField jPassword;
        private javax.swing.JTextField jTCorreo;
        // End of variables declaration//GEN-END:variables

        /**
         * Método para leer el archivo de usuarios
         */
        private void leerArchivoUsuarios() {
                try{
                        
                        if (usuarios == null) {
                                System.out.println("Error: El archivo usuarios.txt no existe dentro del JAR.");
                                return;
                            }
                        BufferedReader br = new BufferedReader(new FileReader(usuarios));
                        String linea;
                        while((linea = br.readLine()) != null ){
                                //String[] informacion = linea.split(";");
                                //Orden Nombre; Apellidos; Contraseña; Cedula; Telefono; Correo, Estado
                                usuariosLista.add(linea);
                        }
                        br.close();
                }catch(IOException ex){
                        System.out.println("Error al leer el archivo de usuarios: " + ex.getMessage());
                }
        }

        private void leerArchivoHabitaciones() {
                try{
                        
                        if(habitaciones == null){
                                System.out.println("Error: El archivo habitaciones.txt no existe dentro del JAR.");
                                return;
                        }
                        BufferedReader br = new BufferedReader(new FileReader(habitaciones));
                        String linea;
                        while((linea = br.readLine()) != null){
                                //String[] informacion = linea.split(";");
                                //Orden numero;tipo;precio;estado
                                habitacionesLista.add(linea);
                        }
                }catch(IOException ex){
                        System.out.println("Error al leer el archivo de habitaciones: " + ex.getMessage());
                }
        }

        private void leerArchivoReservas() {
                try{
                        if(reservas == null){
                                System.out.println("Error: El archivo reservas.txt no existe dentro del JAR.");
                                return;
                        }
                        BufferedReader br = new BufferedReader(new FileReader(reservas));
                        String linea;
                        while((linea = br.readLine()) != null){
                                //String[] informacion = linea.split(";");
                                //Orden numero;diaInicio;mesInicio;anioInicio;diaFin;mesFin;anioFin;estado
                                reservasLista.add(linea);
                        }
                }catch(IOException ex){
                        System.out.println("Error al leer el archivo de reservas: " + ex.getMessage());
                }
        }
        
        private void leerArchivoEstancias(){
                try{
                        BufferedReader br = new BufferedReader(new FileReader(estanciasArchivo));
                        String linea;
                        while((linea = br.readLine()) != null){
                                //String[] informacion = linea.split(";");
                                //Orden numero;idCliente;idReserva;estado
                                estanciasLista.add(linea);
                        }
                }catch(IOException ex){
                        System.out.println("Error al leer el archivo de estancias: " + ex.getMessage());
                }
        }
        
        protected static  void escribirArchivoReservas(){
                try{
//                        //Si no existe el archivo, se crea una copia
//                        if(!reservasArchivo.exists()){
//                                
//                                if(reservas != null){
//                                        OutputStream salidaArchivo = new FileOutputStream(reservasArchivo);
//                                        
//                                        byte[] buffer = new byte[1024];
//                                        int longitud;
//                                        while((longitud = reservas.read(buffer)) > 0){
//                                                salidaArchivo.write(buffer, 0, longitud);
//                                        }
//                                        
//                                        salidaArchivo.close();
//                                        reservas.close();
//                                }
//                        }else{
//                                reservasArchivo.createNewFile();
//                        }
//                        
//                        OutputStream os = new FileOutputStream(reservasArchivo, true);
//                        String nuevaLinea = reserva;
//                        
//                        byte[] datosEnBytes = nuevaLinea.getBytes("UTF-8");
//                        
//                        os.write(datosEnBytes);
//                        
//                        os.flush();
//                        os.close();
                        
                        BufferedWriter bw = new BufferedWriter(new FileWriter(reservasArchivo));
                        for(String reserva : reservasLista){
                                bw.append(reserva);
                                bw.newLine();
                        }
                        bw.close();
                        
                }catch(IOException ex){
                        System.out.println("Error al escribir en el archivo de reservas: " + ex.getMessage());
                }
        }
        
        protected static void escribirArchivoHabitaciones(){
                try{
                        BufferedWriter bw = new BufferedWriter(new FileWriter(habitacionesArchivo));
                        for(String habitacion : habitacionesLista){
                                bw.append(habitacion);
                                bw.newLine();
                        }
                        bw.close();

                }catch(IOException ex){
                        System.out.println("Error al escribir en el archivo de habitaciones: " + ex.getMessage());
                }
        }
        
        protected static void escribirArchivoUsuarios(){
                try{
                        BufferedWriter bw = new BufferedWriter(new FileWriter(usuarios));
                        for(String usuario : usuariosLista){
                                bw.append(usuario);
                                bw.newLine();
                        }
                        bw.close();
                        
                }catch(IOException ex){
                        System.out.println("Error al escribir en el archivo de clientes: " + ex.getMessage());
                }
        }
        
        protected static void escribirArchivoEstancias(){
                try{
                        BufferedWriter bw = new BufferedWriter(new FileWriter(estanciasArchivo));
                        for(String estancia : estanciasLista){
                                bw.append(estancia);
                                bw.newLine();
                        }
                        bw.close();
                        
                }catch(IOException ex){
                        System.out.println("Error al escribir en el archivo de estancias: " + ex.getMessage());
                }
        }
        
        protected static void cambiarEstadoHabitacion(String id, String nuevoEstado){
                for (int i = 0; i < habitacionesLista.size(); i++) {
                        String habitacionActual = habitacionesLista.get(i);
                        String[] informacion = habitacionActual.split(";");

                        // Si encontramos la habitación por su ID
                        if (informacion[0].equals(id)) {
                            informacion[3] = nuevoEstado; // Modificamos el estado en el arreglo

                            // Reconstruimos la cadena de texto de la habitación
                            String estanciaModificada = informacion[0] + ";" + informacion[1] + ";" + informacion[2] + ";" + informacion[3];

                            // PASO CLAVE: Guardamos los cambios de vuelta en la lista real usando el índice 'i'
                            habitacionesLista.set(i, estanciaModificada);

                            break; // Rompemos el ciclo porque ya encontramos y modificamos la habitación
                        }
                    }
        }
        
        protected static void cambiarEstadoEstancia(String id, String nuevoEstado){
                for (int i = 0; i < estanciasLista.size(); i++) {
                        String estanciaActual = estanciasLista.get(i);
                        String[] informacion = estanciaActual.split(";");

                        // Si encontramos la habitación por su ID
                        if (informacion[0].equals(id)) {
                            informacion[3] = nuevoEstado; // Modificamos el estado en el arreglo

                            // Reconstruimos la cadena de texto de la habitación
                            String habitacionModificada = informacion[0] + ";" + informacion[1] + ";" + informacion[2] + ";" + informacion[3];

                            // PASO CLAVE: Guardamos los cambios de vuelta en la lista real usando el índice 'i'
                            habitacionesLista.set(i, habitacionModificada);

                            break; // Rompemos el ciclo porque ya encontramos y modificamos la habitación
                        }
                    }
        }
        
        protected static void eliminarReserva(String id){
                Iterator<String> iterador = reservasLista.iterator();
                
                while (iterador.hasNext()){
                        String[] informacion = iterador.next().split(";");
                        
                        if(informacion[0].equals(id)){
                                iterador.remove();
                                
                                JOptionPane.showMessageDialog(null, "Reserva eliminada", "Confirmacion reserva eliminada", 1);
                        }
                }
        }
        
        protected static int buscarClientePorCorreo(String correo){
                int id = 0;
                for(int i = 0; i < usuariosLista.size(); i++){
                        String[] usuario = usuariosLista.get(i).split(";");
                        if(usuario[5].equals(correo)){
                                id = i;
                        }
                }
                return id;
        }
        
        protected static String buscarHabitacionPorId(String id){
                String habitacionBuscada = "";
                for(String habitacion : habitacionesLista){
                        if(habitacion.split(";")[0].equals(id)){
                                habitacionBuscada = habitacion;
                        }
                }
                
                return habitacionBuscada;
        }
        
        protected static String buscarEstanciaPorId(String id){
                String estanciaBuscada = "";
                for(String estancia : estanciasLista){
                        if(estancia.split(";")[0].equals(id)){
                                estanciaBuscada = estancia;
                        }
                }
                
                return estanciaBuscada;
        }
        
        protected static String buscarReservaPorId(String id) {
                String reservaBuscada = "";
                for(String reserva : reservasLista){
                        if(reserva.split(";")[1].equals(id)){
                                reservaBuscada = reserva;
                        }
                }
                
                return reservaBuscada;
        }
        
        /**
         * Metodo para verificar si un correo electronico existe en el registro
         * @param correo
         * @return 
         */
        protected static Boolean verificarCorreoExiste(String correo){
                Boolean correoExiste = false;
                
                for(String usuario : usuariosLista){
                        String[] linea = usuario.split(";");
                        if(linea[5].equalsIgnoreCase(correo)){
                                correoExiste = true;
                                break;
                        }
                }
                return correoExiste;
        }
}
