/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.pantallas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class RegistrarIngreso extends javax.swing.JFrame {

        /**
         * Creates new form RegistrarIngreso
         */
        public RegistrarIngreso() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
                
                jCBCliente.setModel(Login.modeloClientes);
                jCBReserva.setModel(Login.modeloReservas);
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLCliente = new javax.swing.JLabel();
                jCBReserva = new javax.swing.JComboBox<>();
                jBConfirmar = new javax.swing.JButton();
                jLReserva1 = new javax.swing.JLabel();
                jCBCliente = new javax.swing.JComboBox<>();

                setTitle("Registrar Ingreso Cliente");

                jLTitulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo.setText("Registrar ingreso del cliente");

                jPRegistro.setOpaque(false);

                jLCliente.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLCliente.setForeground(new java.awt.Color(0, 0, 0));
                jLCliente.setText("Cliente");

                jCBReserva.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBReserva.setForeground(new java.awt.Color(255, 255, 255));

                jBConfirmar.setBackground(new java.awt.Color(153, 255, 153));
                jBConfirmar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBConfirmar.setForeground(new java.awt.Color(0, 0, 0));
                jBConfirmar.setText("Confirmar");
                jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBConfirmarActionPerformed(evt);
                        }
                });

                jLReserva1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLReserva1.setForeground(new java.awt.Color(0, 0, 0));
                jLReserva1.setText("Reserva");

                jCBCliente.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBCliente.setForeground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLReserva1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jCBCliente, 0, 334, Short.MAX_VALUE)
                                                        .addComponent(jCBReserva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGap(217, 217, 217)
                                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(189, Short.MAX_VALUE))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLReserva1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(49, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(143, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(56, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
                if(jCBCliente.getSelectedIndex() == 0 || jCBReserva.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(null, "Seleccione los datos", "Error Seleccion Datos", 0);
                }else{
                        String clienteId = Integer.toString(Login.buscarClientePorCorreo(jCBCliente.getSelectedItem().toString().split(";")[5]));
                        String reservaId = jCBReserva.getSelectedItem().toString().split(";")[0];
                        Login.estanciasLista.add("001;" + clienteId + ";" + reservaId + ";" + "ingresado");
                        Login.modeloEstancias.addElement("001;" + clienteId + ";" + reservaId + ";" + "ingresado");
                        Login.escribirArchivoEstancias();
                        JOptionPane.showMessageDialog(null, "Ingreso registrado", "Confirmación Ingreso", 1);
                }
        }//GEN-LAST:event_jBConfirmarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(RegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(RegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(RegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(RegistrarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new RegistrarIngreso().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBConfirmar;
        private javax.swing.JComboBox<String> jCBCliente;
        private javax.swing.JComboBox<String> jCBReserva;
        private javax.swing.JLabel jLCliente;
        private javax.swing.JLabel jLReserva1;
        private javax.swing.JLabel jLTitulo;
        private javax.swing.JPanel jPRegistro;
        // End of variables declaration//GEN-END:variables
}
