/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.pantallas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class RegistroCliente extends javax.swing.JFrame {

        /**
         * Creates new form RegistroCliente
         */
        public RegistroCliente() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo1 = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLCorreo = new javax.swing.JLabel();
                jTCorreo = new javax.swing.JTextField();
                jLContrasenia = new javax.swing.JLabel();
                jBCrearCuenta = new javax.swing.JButton();
                jLNombres = new javax.swing.JLabel();
                jTNombres = new javax.swing.JTextField();
                jLApellidos = new javax.swing.JLabel();
                jTApellidos = new javax.swing.JTextField();
                jLCedula = new javax.swing.JLabel();
                jTCedula = new javax.swing.JTextField();
                jLTelefono = new javax.swing.JLabel();
                jTTelefono = new javax.swing.JTextField();
                jPasswordVerificar = new javax.swing.JPasswordField();
                jLContrasenia1 = new javax.swing.JLabel();
                jPassword = new javax.swing.JPasswordField();

                setTitle("Registro Cliente");

                jLTitulo1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo1.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo1.setText("Registro Cliente");

                jPRegistro.setOpaque(false);

                jLCorreo.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLCorreo.setForeground(new java.awt.Color(0, 0, 0));
                jLCorreo.setText("Correo");

                jTCorreo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTCorreo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTCorreoActionPerformed(evt);
                        }
                });

                jLContrasenia.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLContrasenia.setForeground(new java.awt.Color(0, 0, 0));
                jLContrasenia.setText("Contraseña");

                jBCrearCuenta.setBackground(new java.awt.Color(153, 255, 153));
                jBCrearCuenta.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBCrearCuenta.setForeground(new java.awt.Color(0, 0, 0));
                jBCrearCuenta.setText("Crear Cuenta");
                jBCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBCrearCuentaActionPerformed(evt);
                        }
                });

                jLNombres.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLNombres.setForeground(new java.awt.Color(0, 0, 0));
                jLNombres.setText("Nombres");

                jTNombres.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTNombres.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTNombresActionPerformed(evt);
                        }
                });

                jLApellidos.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLApellidos.setForeground(new java.awt.Color(0, 0, 0));
                jLApellidos.setText("Apellidos");

                jTApellidos.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTApellidos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTApellidosActionPerformed(evt);
                        }
                });

                jLCedula.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLCedula.setForeground(new java.awt.Color(0, 0, 0));
                jLCedula.setText("Cédula");

                jTCedula.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTCedula.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTCedulaActionPerformed(evt);
                        }
                });

                jLTelefono.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLTelefono.setForeground(new java.awt.Color(0, 0, 0));
                jLTelefono.setText("Teléfono");

                jTTelefono.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jTTelefono.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTTelefonoActionPerformed(evt);
                        }
                });

                jLContrasenia1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLContrasenia1.setForeground(new java.awt.Color(0, 0, 0));
                jLContrasenia1.setText("Verificar Contraseña");

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jBCrearCuenta)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addComponent(jLCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                                .addComponent(jTCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(101, 101, 101))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(101, 101, 101))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLContrasenia1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                                                .addComponent(jPasswordVerificar)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLCorreo)
                                        .addComponent(jLCedula))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLNombres)
                                        .addComponent(jLTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLApellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jLContrasenia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLContrasenia1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jBCrearCuenta)
                                .addGap(22, 22, 22))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(265, 265, 265)
                                                .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(73, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(46, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearCuentaActionPerformed
                if(jTNombres.getText().isEmpty() || jTApellidos.getText().isEmpty() || new String(jPassword.getPassword()).isEmpty() || jTCedula.getText().isEmpty() || jTTelefono.getText().isEmpty() || jTCorreo.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "¡Ingrese los datos!", "Error Espacios en Blanco", 0);
                }else{         
                        //Verificar que el correo no exista en el registro
                        if(Login.verificarCorreoExiste(jTCorreo.getText().trim())){
                                JOptionPane.showMessageDialog(null, "¡El correo ya existe!", "Error Correo", 0);
                        }else{
                                //Si las contraseñas coinciden
                                if(new String(jPasswordVerificar.getPassword()).trim().equals(new String(jPassword.getPassword()).trim())){
                                        String usuarioNuevo = jTNombres.getText().trim() + ";" + jTApellidos.getText().trim() + ";" + new String(jPassword.getPassword()).trim() + ";" + jTCedula.getText().trim() + ";" + jTTelefono.getText().trim() + ";" + jTCorreo.getText().trim() + ";" + "cliente";
                                        Login.usuariosLista.add(usuarioNuevo);
                                        Login.modeloClientes.addElement(usuarioNuevo);
                                        Login.escribirArchivoUsuarios();
                                        limpiarInterfaz();
                                        JOptionPane.showMessageDialog(null, "Se registró el cliente", "Confirmación Registro", 1);

                                }else{
                                        //Si no coinciden
                                        JOptionPane.showMessageDialog(null, "Contraseñas no coinciden", "Error contraseñas", 0);
                                }
                        }
                        
                }
        }//GEN-LAST:event_jBCrearCuentaActionPerformed

        private void jTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTCorreoActionPerformed

        private void jTNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombresActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTNombresActionPerformed

        private void jTApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidosActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTApellidosActionPerformed

        private void jTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCedulaActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTCedulaActionPerformed

        private void jTTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTelefonoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTTelefonoActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new RegistroCliente().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBCrearCuenta;
        private javax.swing.JLabel jLApellidos;
        private javax.swing.JLabel jLCedula;
        private javax.swing.JLabel jLContrasenia;
        private javax.swing.JLabel jLContrasenia1;
        private javax.swing.JLabel jLCorreo;
        private javax.swing.JLabel jLNombres;
        private javax.swing.JLabel jLTelefono;
        private javax.swing.JLabel jLTitulo1;
        private javax.swing.JPanel jPRegistro;
        private javax.swing.JPasswordField jPassword;
        private javax.swing.JPasswordField jPasswordVerificar;
        private javax.swing.JTextField jTApellidos;
        private javax.swing.JTextField jTCedula;
        private javax.swing.JTextField jTCorreo;
        private javax.swing.JTextField jTNombres;
        private javax.swing.JTextField jTTelefono;
        // End of variables declaration//GEN-END:variables

        private void limpiarInterfaz() {
                jTCorreo.setText("");
                jTNombres.setText("");
                jTApellidos.setText("");
                jTCedula.setText("");
                jPassword.setText("");
                jPasswordVerificar.setText("");
                jTTelefono.setText("");
        }
}
