/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.com.sistemahotel.pantallas;

import java.awt.Color;
import java.time.LocalDate;
import java.time.Month;
import java.time.Year;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Reserva extends javax.swing.JFrame {

        /**
         * Creates new form Reserva
         */
        public Reserva() {
                initComponents();
                setResizable(false);
                getContentPane().setBackground(new Color(204, 198, 180));
                
                //Poblar combo box de dias a partir del dia actual
                for(int dia = LocalDate.now().getDayOfMonth(); dia <= 31; dia++){
                        jCBFIDia.addItem(Integer.toString(dia));
                        jCBFFDia.addItem(Integer.toString(dia));
                }
                //Combo box de meses a partir del dia actual
                for(int mes = LocalDate.now().getMonthValue(); mes <= 12; mes++){
                        jCBFIMes.addItem(Integer.toString(mes));
                        jCBFFMes.addItem(Integer.toString(mes));
                }
                //Combo box de años
                int anioActual = Year.now().getValue();
                jCBFIAnio.addItem(Integer.toString(anioActual));
                jCBFFAnio.addItem(Integer.toString(anioActual));
                jCBFFAnio.addItem(Integer.toString(anioActual + 1));
                
                jCBHabitaciones.setModel(Login.modeloHabitaciones);
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLTitulo = new javax.swing.JLabel();
                jPRegistro = new javax.swing.JPanel();
                jLDiaInicio = new javax.swing.JLabel();
                jCBFIDia = new javax.swing.JComboBox<>();
                jLHabitacion1 = new javax.swing.JLabel();
                jCBHabitaciones = new javax.swing.JComboBox<>();
                jLFechaInicio1 = new javax.swing.JLabel();
                jCBFIMes = new javax.swing.JComboBox<>();
                jLMesInicio = new javax.swing.JLabel();
                jCBFIAnio = new javax.swing.JComboBox<>();
                jLAnioInicio = new javax.swing.JLabel();
                jLFechaFin = new javax.swing.JLabel();
                jCBFFDia = new javax.swing.JComboBox<>();
                jLDiaFin = new javax.swing.JLabel();
                jCBFFMes = new javax.swing.JComboBox<>();
                jLMesFin = new javax.swing.JLabel();
                jCBFFAnio = new javax.swing.JComboBox<>();
                jLAnioFin = new javax.swing.JLabel();
                jBConfirmar = new javax.swing.JButton();

                setTitle("Reserva Habitación");
                setBackground(new java.awt.Color(255, 255, 255));

                jLTitulo.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
                jLTitulo.setForeground(new java.awt.Color(102, 102, 255));
                jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLTitulo.setText("Sistema de Reservas");

                jPRegistro.setOpaque(false);

                jLDiaInicio.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLDiaInicio.setForeground(new java.awt.Color(0, 0, 0));
                jLDiaInicio.setText("Día");

                jCBFIDia.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBFIDia.setForeground(new java.awt.Color(255, 255, 255));

                jLHabitacion1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLHabitacion1.setForeground(new java.awt.Color(0, 0, 0));
                jLHabitacion1.setText("Habitación");

                jCBHabitaciones.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBHabitaciones.setForeground(new java.awt.Color(255, 255, 255));

                jLFechaInicio1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLFechaInicio1.setForeground(new java.awt.Color(0, 0, 0));
                jLFechaInicio1.setText("Fecha inicio");

                jCBFIMes.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBFIMes.setForeground(new java.awt.Color(255, 255, 255));

                jLMesInicio.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLMesInicio.setForeground(new java.awt.Color(0, 0, 0));
                jLMesInicio.setText("Mes");

                jCBFIAnio.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBFIAnio.setForeground(new java.awt.Color(255, 255, 255));

                jLAnioInicio.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLAnioInicio.setForeground(new java.awt.Color(0, 0, 0));
                jLAnioInicio.setText("Año");

                jLFechaFin.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLFechaFin.setForeground(new java.awt.Color(0, 0, 0));
                jLFechaFin.setText("Fecha fin");

                jCBFFDia.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBFFDia.setForeground(new java.awt.Color(255, 255, 255));

                jLDiaFin.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLDiaFin.setForeground(new java.awt.Color(0, 0, 0));
                jLDiaFin.setText("Día");

                jCBFFMes.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBFFMes.setForeground(new java.awt.Color(255, 255, 255));

                jLMesFin.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLMesFin.setForeground(new java.awt.Color(0, 0, 0));
                jLMesFin.setText("Mes");

                jCBFFAnio.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
                jCBFFAnio.setForeground(new java.awt.Color(255, 255, 255));

                jLAnioFin.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
                jLAnioFin.setForeground(new java.awt.Color(0, 0, 0));
                jLAnioFin.setText("Año");

                jBConfirmar.setBackground(new java.awt.Color(153, 255, 153));
                jBConfirmar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
                jBConfirmar.setForeground(new java.awt.Color(0, 0, 0));
                jBConfirmar.setText("Confirmar");
                jBConfirmar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBConfirmarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPRegistroLayout = new javax.swing.GroupLayout(jPRegistro);
                jPRegistro.setLayout(jPRegistroLayout);
                jPRegistroLayout.setHorizontalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLHabitacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLFechaInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jCBHabitaciones, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                                .addComponent(jCBFIDia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(jCBFIMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jCBFIAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLAnioInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                                                .addComponent(jCBFFDia, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLDiaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCBFFMes, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLMesFin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(24, 24, 24)
                                                .addComponent(jCBFFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLAnioFin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(41, Short.MAX_VALUE))
                );
                jPRegistroLayout.setVerticalGroup(
                        jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPRegistroLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLHabitacion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLFechaInicio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCBFIDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLDiaInicio)
                                        .addComponent(jCBFIMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCBFIAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLAnioInicio)
                                        .addComponent(jLMesInicio))
                                .addGap(30, 30, 30)
                                .addComponent(jLFechaFin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCBFFDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLDiaFin)
                                                .addComponent(jCBFFMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLMesFin)
                                                .addComponent(jCBFFAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLAnioFin)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jBConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(54, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(43, Short.MAX_VALUE)
                                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jBConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarActionPerformed
                if(jCBHabitaciones.getSelectedIndex() == 0){
                        JOptionPane.showMessageDialog(null, "¡Seleccione una habitación!", "Error Selección Habitación", 0);
                }else{
                        
                        int anioInicio = Integer.parseInt(jCBFIAnio.getSelectedItem().toString());
                        int mesInicio = Integer.parseInt(jCBFIMes.getSelectedItem().toString());
                        int diaInicio = Integer.parseInt(jCBFIDia.getSelectedItem().toString());
                        
                        int anioFin = Integer.parseInt(jCBFFAnio.getSelectedItem().toString());
                        int mesFin = Integer.parseInt(jCBFFMes.getSelectedItem().toString());
                        int diaFin = Integer.parseInt(jCBFFDia.getSelectedItem().toString());
                        
                        LocalDate fechaInicio = LocalDate.of(anioInicio, mesInicio, diaInicio);
                        LocalDate fechaFin = LocalDate.of(anioFin, mesFin, diaFin);
                        //Verificar que la fecha de inicio sea antes de la fecha fin
                        if(fechaFin.isAfter(fechaInicio) || fechaFin.isEqual(fechaInicio)){
                                String[] habitacion = jCBHabitaciones.getSelectedItem().toString().split(",");
                                String reserva = "005;" + habitacion[0] + ";" + jCBFIDia.getSelectedItem().toString() + ";" + jCBFIMes.getSelectedItem().toString() + ";" + jCBFIAnio.getSelectedItem().toString() + ";" + jCBFFDia.getSelectedItem().toString() + ";" + jCBFFMes.getSelectedItem().toString() + ";" + jCBFFAnio.getSelectedItem().toString();
                                int idHabitacion = jCBHabitaciones.getSelectedIndex();
                                Login.reservasLista.add(reserva);
                                Login.modeloReservas.addElement(reserva);
                                Login.escribirArchivoReservas();
                                Login.cambiarEstadoHabitacion(habitacion[0], "ocupada");
                                Login.modeloHabitaciones.removeElementAt(idHabitacion);
                                Login.escribirArchivoHabitaciones();
                                limpiarInterfaz();
                                JOptionPane.showMessageDialog(null, "Se registró la reserva", "Confirmación Registro", 1);
                        }else{
                                JOptionPane.showMessageDialog(null, "¡Fecha de Fin incorrecta!", "Error Fecha", 0);
                        }
                        
                }
        }//GEN-LAST:event_jBConfirmarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Reserva().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBConfirmar;
        private javax.swing.JComboBox<String> jCBFFAnio;
        private javax.swing.JComboBox<String> jCBFFDia;
        private javax.swing.JComboBox<String> jCBFFMes;
        private javax.swing.JComboBox<String> jCBFIAnio;
        private javax.swing.JComboBox<String> jCBFIDia;
        private javax.swing.JComboBox<String> jCBFIMes;
        private javax.swing.JComboBox<String> jCBHabitaciones;
        private javax.swing.JLabel jLAnioFin;
        private javax.swing.JLabel jLAnioInicio;
        private javax.swing.JLabel jLDiaFin;
        private javax.swing.JLabel jLDiaInicio;
        private javax.swing.JLabel jLFechaFin;
        private javax.swing.JLabel jLFechaInicio1;
        private javax.swing.JLabel jLHabitacion1;
        private javax.swing.JLabel jLMesFin;
        private javax.swing.JLabel jLMesInicio;
        private javax.swing.JLabel jLTitulo;
        private javax.swing.JPanel jPRegistro;
        // End of variables declaration//GEN-END:variables

        private void limpiarInterfaz() {
               jCBHabitaciones.setSelectedIndex(0);
               jCBFIDia.setSelectedIndex(0);
               jCBFIMes.setSelectedIndex(0);
               jCBFIAnio.setSelectedIndex(0);
               jCBFFDia.setSelectedIndex(0);
               jCBFFMes.setSelectedIndex(0);
               jCBFFAnio.setSelectedIndex(0);
        }
}
